/* Issuer scoped points: business samples and payment methods have separate rules. */
(() => {
  'use strict';
  const account=document.getElementById('account'), buy=document.getElementById('find');
  if(!account||!buy)return;
  const el=id=>document.getElementById(id), safe=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const section=(p,h)=>{const s=document.createElement('section');s.className='panel points-panel';s.innerHTML=h;p.append(s)};
  section(account,`<style>.points-panel input[type="checkbox"]{width:auto;margin:0 8px 0 0;padding:0;vertical-align:middle}</style><h2>我的服务积分</h2><p class="sub">每个提供方发行自己的积分。实际服务后增加提供方持有的自家积分；别人愿意接受，才能兑换他们的服务。前十次样品跳过所有结算。</p>
    <p id="pointsIdentity"></p><button class="ghost" id="pointsRefresh">刷新账本</button><button class="ghost" id="pointsHoldings">核对我持有的各家积分</button><div id="pointsBalances"></div><div id="pointsDebts"></div>
    <h3>发行设置</h3><label><input type="checkbox" id="pointsIssue">允许新发行积分</label><label><input type="checkbox" id="pointsHTTP">允许通过 HTTP 连接本机实验节点</label><button id="pointsSettings">保存发行设置</button>
    <h3>我的 Agent 服务规则</h3><label>选择供给<select id="pointsService"></select></label><label><input type="checkbox" id="pointsEnabled">启用积分服务</label><label>每次服务的自家积分数量<input id="pointsAmount" inputmode="numeric" value="1"></label>
    <label><input type="checkbox" id="pointsEarn">允许免费服务后产生我的积分</label><label><input type="checkbox" id="pointsDebt">允许使用方欠账，同时产生我的积分</label><label><input type="checkbox" id="pointsPay">接受已有积分支付（只转移余额）</label><label>每个使用方最多可欠多少自家积分<input id="pointsDebtCap" inputmode="numeric" value="0"></label><button id="pointsSaveService">保存这项服务规则</button>
    <h3>连接一个积分发行方</h3><label>对方节点地址<input id="pointsPeer" placeholder="https://节点地址"></label><button id="pointsConnect">核对身份并连接</button><div id="pointsPeers"></div>
    <h3>我愿意接受哪些积分</h3><label>对方发行方<select id="pointsAcceptedIssuer"></select></label><label><input type="checkbox" id="pointsAcceptEnabled" checked>愿意接受</label>
    <p class="sub">兑换比例由你决定：每收到下面数量的对方积分，愿意给出对应数量的自家积分或服务价值。</p><label>对方积分数量<input id="pointsDenominator" inputmode="numeric" value="1"></label><label>认可为多少自家积分<input id="pointsNumerator" inputmode="numeric" value="1"></label>
    <label>单笔接收上限<input id="pointsPerTrade" inputmode="numeric" value="10"></label><label>每天接收上限<input id="pointsDaily" inputmode="numeric" value="100"></label><label>最多持有对方积分<input id="pointsMaxHolding" inputmode="numeric" value="100"></label><button id="pointsSaveAcceptance">保存接受条件</button><div id="pointsAcceptance"></div>
    <h3>主动给使用方加我的积分</h3><label>使用方身份<input id="pointsHolder" placeholder="对方节点 DID"></label><label>积分数量<input id="pointsGrantAmount" inputmode="numeric" value="1"></label><label>来源<select id="pointsGrantMode"><option value="ISSUE">新发行到使用方账户</option><option value="TRANSFER">从我的存量转给使用方</option></select></label><label>双方约定的备注<input id="pointsGrantMemo" maxlength="256"></label><button id="pointsGrant">明确加积分</button>
    <h3>偿还我的积分欠账</h3><label>发行方<select id="pointsDebtIssuer"></select></label><label>偿还数量<input id="pointsRepayAmount" inputmode="numeric" value="1"></label><button id="pointsRepay">用我持有的对方积分偿还</button>
    <h3>两方或三方互换</h3><p class="sub">各方按自己的接受表同意，全部成功才完成交换。你给第一方自家积分；第一方给第二方或你自家积分；三方模式中第二方再给你自家积分。</p><label>第一方<select id="pointsSwapFirst"></select></label><label>我给第一方多少自家积分<input id="pointsSwapMine" inputmode="numeric" value="1"></label><label>第二方（两方互换留空）<select id="pointsSwapSecond"><option value="">直接换回给我</option></select></label><label>第一方给出多少自家积分<input id="pointsSwapFirstAmount" inputmode="numeric" value="1"></label><label>三方模式中第二方给我多少自家积分<input id="pointsSwapSecondAmount" inputmode="numeric" value="1"></label><button id="pointsSwap">明确按上述条件互换</button>
    <h3>兑换与服务结算记录</h3><div id="pointsOrders"></div>`);
  section(buy,`<h2>用积分兑换服务</h2><p class="sub">在上方交易条件中选择积分方式。免费增积分、欠账和已有积分支付都需要你接受具体条件；前十次样品直接免费调用。兑换最多三跳，找不到可接受路径时不会付款。</p><label>已有积分支付时使用哪家的积分<select id="pointsFundingIssuer"><option value="">使用服务提供方的积分</option></select></label><label>最多愿意使用多少该发行方积分<input id="pointsMaxCost" inputmode="numeric" placeholder="留空按可用余额寻路"></label>`);
  let state={services:[],acceptance:[],peers:[],holdings:[]};
  const labels={READY:'已保存条件',PREPARED:'各方已预留，尚未执行服务',EXECUTING:'服务执行中',UNKNOWN:'结果待核对',COMMITTING:'整体提交已决定，等待各方回正',ABORTING:'整体中止已决定，等待释放预留',CONFIRMED:'各方已完成结算',FAILED:'整体中止'};
  const options=peers=>peers.map(p=>`<option value="${safe(p.did)}">${safe(p.did.slice(-16))}</option>`).join('');
  function serviceForm(){const s=state.services.find(s=>s.service_id===el('pointsService').value);el('pointsEnabled').checked=!!s?.enabled;el('pointsAmount').value=s?.amount_decimal||String(s?.amount??1);for(const [id,mode]of[['pointsEarn','EARN'],['pointsDebt','DEBT'],['pointsPay','PAY']])el(id).checked=s?.modes.includes(mode)||false;el('pointsDebtCap').value=s?.debt_limit_decimal||String(s?.debt_limit??0)}
  function acceptanceForm(){const a=state.acceptance.find(a=>a.issuer_did===el('pointsAcceptedIssuer').value);if(!a)return;el('pointsAcceptEnabled').checked=a.enabled;for(const [id,key]of[['pointsNumerator','numerator'],['pointsDenominator','denominator'],['pointsPerTrade','per_trade'],['pointsDaily','daily'],['pointsMaxHolding','max_holding']])el(id).value=a[key+'_decimal']||String(a[key])}
  async function load(){const [s,r]=await Promise.all([request('/v1/points'),request('/v1/runtime')]);state=s;el('pointsIdentity').textContent='我的发行身份：'+s.issuer_did;el('pointsIssue').checked=s.settings.issuance_enabled;el('pointsHTTP').checked=s.settings.allow_http;
    el('pointsBalances').innerHTML=(s.balances||[]).map(b=>`<p>${b.holder_did===s.issuer_did?'我持有的自家积分':safe(b.holder_did.slice(-16))+' 持有我的积分'}：${safe(b.amount_decimal)}；预留 ${safe(b.reserved_decimal||b.reserved)}</p>`).join('')||'<p class="sub">我的积分尚无发行记录。</p>';
    el('pointsBalances').innerHTML+=(s.holdings||[]).filter(b=>b.issuer_did!==s.issuer_did).map(b=>`<p>我持有 ${safe(b.issuer_did.slice(-16))} 的积分：${safe(b.amount_decimal)}（上次核对的余额）</p>`).join('');
    el('pointsDebts').innerHTML=Object.entries(s.debts||{}).filter(([,v])=>v).map(([h,v])=>`<p>${safe(h.slice(-16))} 欠我 ${safe(s.debt_decimals?.[h]||v)} 自家积分</p>`).join('');
    const chosen=el('pointsService').value;el('pointsService').innerHTML=(r.published||[]).map(p=>`<option value="${safe(p.service_id)}">${safe(p.card?.name||p.service_id)}</option>`).join('')||'<option value="">先上架一个 Agent</option>';if([...el('pointsService').options].some(o=>o.value===chosen))el('pointsService').value=chosen;serviceForm();
    for(const id of['pointsAcceptedIssuer','pointsDebtIssuer']){const selected=el(id).value;el(id).innerHTML=options(s.peers||[]);if([...el(id).options].some(o=>o.value===selected))el(id).value=selected}acceptanceForm();
    for(const id of['pointsSwapFirst','pointsSwapSecond']){const selected=el(id).value;el(id).innerHTML=(id==='pointsSwapSecond'?'<option value="">直接换回给我</option>':'')+options(s.peers||[]);if([...el(id).options].some(o=>o.value===selected))el(id).value=selected}
    const selected=el('pointsFundingIssuer').value;el('pointsFundingIssuer').innerHTML='<option value="">使用服务提供方的积分</option>'+options([{did:s.issuer_did},...(s.peers||[])]);if([...el('pointsFundingIssuer').options].some(o=>o.value===selected))el('pointsFundingIssuer').value=selected;
    el('pointsPeers').innerHTML=(s.peers||[]).map(p=>`<p>${safe(p.did.slice(-16))} · ${safe(p.endpoint)}</p>`).join('');
    el('pointsAcceptance').innerHTML=(s.acceptance||[]).map(a=>`<p>${safe(a.issuer_did.slice(-16))}：${a.enabled?'接受':'暂停接受'}，${safe(a.denominator_decimal||a.denominator)} 对方积分 → ${safe(a.numerator_decimal||a.numerator)} 自家积分价值</p>`).join('');
    el('pointsOrders').innerHTML=(s.orders||[]).slice().reverse().map(o=>`<article class="agent"><b>${safe(labels[o.state]||o.state)}</b><p>${safe(o.record.terms?.mode||'多方兑换')} · ${safe(o.record.plan_id.slice(-16))}</p><button class="ghost" data-points-order="${safe(o.record.plan_id)}">核对原结算</button>${!o.execution_started&&!o.decision&&['READY','PREPARED','UNKNOWN'].includes(o.state)?`<button class="ghost" data-points-cancel="${safe(o.record.plan_id)}">执行前取消</button>`:''}</article>`).join('')||'<p class="sub">尚无积分结算记录。</p>';
  }
  async function run(b,fn){b.disabled=true;try{await fn();await load()}catch(e){notice(e.message,true)}finally{b.disabled=false}}
  el('pointsService').onchange=serviceForm;el('pointsAcceptedIssuer').onchange=acceptanceForm;
  el('pointsRefresh').onclick=e=>run(e.currentTarget,load);
  el('pointsHoldings').onclick=e=>run(e.currentTarget,async()=>{const r=await request('/v1/points/holdings',{});notice(r.missing_issuers.length?'部分发行方离线，显示已核对的余额。':'各家积分余额已核对。')});
  el('pointsSettings').onclick=e=>run(e.currentTarget,async()=>{await request('/v1/points/configure',{issuance_enabled:el('pointsIssue').checked,allow_http:el('pointsHTTP').checked});notice('发行设置已保存，已有积分和原交易继续有效。')});
  el('pointsSaveService').onclick=e=>run(e.currentTarget,async()=>{const sid=el('pointsService').value,s=state.services.find(s=>s.service_id===sid);const modes=[['pointsEarn','EARN'],['pointsDebt','DEBT'],['pointsPay','PAY']].filter(([id])=>el(id).checked).map(([,mode])=>mode);await request('/v1/points/services',{service_id:sid,expected_revision:s?.revision||0,policy:{enabled:el('pointsEnabled').checked,amount:el('pointsAmount').value.trim(),debt_limit:el('pointsDebtCap').value.trim(),modes}});notice('服务积分规则已保存，前十次仍跳过结算。')});
  el('pointsConnect').onclick=e=>run(e.currentTarget,async()=>{await request('/v1/points/peers',{endpoint:el('pointsPeer').value.trim()});notice('已核对对方签名身份并连接。')});
  el('pointsSaveAcceptance').onclick=e=>run(e.currentTarget,async()=>{const issuer=el('pointsAcceptedIssuer').value,a=state.acceptance.find(a=>a.issuer_did===issuer),policy={enabled:el('pointsAcceptEnabled').checked};for(const[id,k]of[['pointsNumerator','numerator'],['pointsDenominator','denominator'],['pointsPerTrade','per_trade'],['pointsDaily','daily'],['pointsMaxHolding','max_holding']])policy[k]=el(id).value.trim();await request('/v1/points/acceptance',{issuer_did:issuer,policy,expected_revision:a?.revision||0});notice('接受条件已保存，新交易使用新条件。')});
  el('pointsGrant').onclick=e=>run(e.currentTarget,async()=>{await request('/v1/points/grants',{holder_did:el('pointsHolder').value.trim(),amount:el('pointsGrantAmount').value.trim(),mode:el('pointsGrantMode').value,memo:el('pointsGrantMemo').value,command_id:crypto.randomUUID()});notice('积分已记入指定使用方账户。')});
  el('pointsRepay').onclick=e=>run(e.currentTarget,async()=>{const r=await request('/v1/points/repay',{issuer_did:el('pointsDebtIssuer').value,amount:el('pointsRepayAmount').value.trim(),command_id:crypto.randomUUID()});notice(labels[r.state]||r.state)});
  el('pointsSwap').onclick=e=>run(e.currentTarget,async()=>{const first=el('pointsSwapFirst').value,second=el('pointsSwapSecond').value;if(!first||first===second)throw Error('请选择不同的兑换参与方');const operations=[{kind:'TRANSFER',issuer_did:state.issuer_did,from_did:state.issuer_did,to_did:first,amount:el('pointsSwapMine').value.trim()},{kind:'TRANSFER',issuer_did:first,from_did:first,to_did:second||state.issuer_did,amount:el('pointsSwapFirstAmount').value.trim()}];if(second)operations.push({kind:'TRANSFER',issuer_did:second,from_did:second,to_did:state.issuer_did,amount:el('pointsSwapSecondAmount').value.trim()});const r=await request('/v1/points/swap',{operations,command_id:crypto.randomUUID()});notice(labels[r.state]||r.state)});
  document.addEventListener('click',e=>{const b=e.target.closest('[data-points-order],[data-points-cancel]');if(!b)return;run(b,async()=>{const id=b.dataset.pointsOrder||b.dataset.pointsCancel;if(b.dataset.pointsCancel)await request('/v1/points/orders/'+id+'/cancel',{});else{const o=(state.orders||[]).find(o=>o.record.plan_id===id);if(o?.record.offer)await request('/v1/trades/plans/'+id+'/reconcile',{});else await request('/v1/points/orders/'+id+'/reconcile',{})}await refresh()})});
  document.querySelectorAll('.navbtn').forEach(b=>b.addEventListener('click',()=>{if(['account','find'].includes(b.dataset.page))load().catch(e=>notice(e.message,true))}));
  load().catch(()=>{});
})();
