"""Ports separate standardized wire messages from wallet and network choices."""
from typing import Protocol


class WalletSigner(Protocol):
    address: str
    def sign(self, required: dict, requirement: dict, *, now=None) -> dict: ...


class SignatureVerifier(Protocol):
    def verify_signature(self, payload: dict) -> bool: ...


class Facilitator(Protocol):
    def supported(self) -> dict: ...
    def verify(self, payload: dict, requirements: dict) -> dict: ...
    def settle(self, payload: dict, requirements: dict) -> dict: ...


class LedgerObserver(Protocol):
    def anchor(self, payload: dict) -> int: ...
    def observe(self, payload: dict, anchor: int, hint: dict | None = None) -> dict: ...
